services:
  - type: web
    name: cinesuggest
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m scripts.init_db && python -m scripts.seed_movies && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "0"
